name: Run Tests

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest, windows-latest ]
        arch: [ x64 ]
        include:
          - os: macOS-latest
            arch: arm64
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: yarn
      - name: Install
        run: yarn install
      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: yarn lint
      - name: Run tests
        run: yarn test:ci
